# https://vettom.pages.dev/Eks/eks-with-envoy-gateway/

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: external-gateway-proxy-service
        type: ClusterIP
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:

---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: external-gatewayclass
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: external-proxy-config
    namespace: envoy-gateway-system

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway
  namespace: envoy-gateway-system
  annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt-DNS
     external-dns.alpha.kubernetes.io/target: "nginx-external-lb-service.chainomi.link"  # hostname of alb ingress, will route traffic from host names in http route through this
spec:
  gatewayClassName: external-gatewayclass
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTP       # HTTP here because TLS is terminated at the NLB
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-route
  namespace: default

spec:
  parentRefs:
    # - name: external-gateway
    #   namespace: envoy-gateway-system
    #   sectionName: http
    - name: external-gateway
      namespace: envoy-gateway-system
      sectionName: https      
  hostnames:
    - nginx.chainomi.link
    - nginx2.chainomi.link
  #   - "*"    
  rules:
    - matches:
      # -  hostname: nginx.chainomi.link
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: nginx
          port: 80
