# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: chainomi@gmail.com
    # profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-staging
  # ca:
  #   secretName: ca-key-pair      
    solvers:
    - dns01:
        route53:
          region: us-west-2

---
# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  privateKey:
    rotationPolicy: Always
  commonName: flask-api.chainomi.link
  dnsNames:
    - flask-api.chainomi.link
    - flask-api2.chainomi.link
    - flask-api3.chainomi.link
    - flask-api4.chainomi.link
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer