# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: ClusterIP
#   ports:
#    - port: 80
#      targetPort: 80 
#   selector:
#     app: app 
#     tier: ngnix
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: app 
#     tier: nginx
# spec:
#   selector:
#     matchLabels:
#       app: app 
#       tier: nginx
#   replicas: 3
#   template:
#     metadata:
#       name: flask-api
#       labels:
#         app: app 
#         tier: nginx
#         sidecar.istio.io/inject: "true"
#     spec:
#       containers:
#         - name: nginx
#           image: httpd         
#           resources:
#             limits:
#               cpu: 500m
#               memory: 512Mi
#             requests:
#               cpu: 500m
#               memory: 512Mi  
#           ports:
#           - containerPort: 80
#             name: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: flask-api-service
spec:
  type: ClusterIP
  ports:
   - port: 8000 
     targetPort: 8000 
  selector:
    app: app 
    tier: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  labels:
    app: app 
    tier: api
spec:
  selector:
    matchLabels:
      app: app 
      tier: api
  replicas: 1
  template:
    metadata:
      name: flask-api
      labels:
        app: app 
        tier: api
        # sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: flask-api
          image: 488144151286.dkr.ecr.us-west-1.amazonaws.com/flask-api:latest #change      
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi  
          ports:
          - containerPort: 8000
            name: flask-api
      serviceAccountName: flask-api-rbac         


