apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-api-rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flask-api-rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-api-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flask-api-rbac
subjects:
- kind: ServiceAccount
  name: flask-api-rbac